apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["echo Hello From Writer Container > /data/message.txt && sleep 3600"]
    volumeMounts:
      - mountPath: /data
        name: shared-data
  - name: reader
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["sleep 10 && cat /data/message.txt && sleep 3600"]
    volumeMounts:
      - mountPath: /data
        name: shared-data
  volumes:
  - name: shared-data
    emptyDir: {}