---
# tasks file for roles/db
- name: Install PostgreSQL
  apt:
    name: postgresql 
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is Running
  service: 
    name: postgresql
    state: started
    enabled: true

- name: create application database
  become: true
  shell: |
    sudo -u postgres psql -tc "SELECT 1 FROM pg_database where datname = 'myapp' " | grep -q 1 ||
    sudo -u postgres psql -c "CREATE DATABASE myapp;"
  args:
    executable: /bin/bash

- name: create PostgreSQL User with password
  become: true
  shell: |
    sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname = '{{ DB_USER }}' " | grep -q 1 ||
    sudo -u postgres psql -c "CREATE USER {{ DB_USER }} WITH PASSWORD '{{ DB_PASS }}';"
  args:
    executable: /bin/bash